### ISSUE TITLE
Visually pleasing and easy to understand home page

### ISSUE THREAD

**Issue by NicoleJackson89** [NicoleJackson89/pp4-recipe-share#1]
As a **New User / Visitor** I can **see a visually pleasing and easy to understand webpage** so that **I am drawn in to sign up and use the webpage**

### Acceptance Criteria

- The home page features recipe posts
- Sign up is displayed in the navigation bar where the potential new user can sign up and share their recipes
- Other pages are easily navigated from the navigation bar on the home page 
- The purpose of the web page is evident to New Users / Visitor 

### Tasks

- [x] Design the homepage to display recipe posts 
- [x] Ensure a sign up link is available for new users in the navigation bar
- [x] Ensure smooth navigation to the other pages
