### ISSUE TITLE
New User account registration

### ISSUE THREAD

**Issue by NicoleJackson89** [NicoleJackson89/pp4-recipe-share#3]
As a **New Site User** I can **sign up for a new account** so that **I am able to share my recipe posts**

### Acceptance Criteria

- Sign up needs to be accessible on the homepage for new users to register a new account
- Sign in needs to be accessible on the homepage for users to login to their account
- Signed in users have full access to the webpages functionality
- Users can logout of their accounts form any page in the navigation bar

### Tasks

- [x] New users can sign up with their email, username and create a private password
- [x] Add recipe post function for logged in users
- [x] Notification to user once account has been created successfully
