### ISSUE TITLE
View Recipe posts

### ISSUE THREAD

**Issue by NicoleJackson89** [NicoleJackson89/pp4-recipe-share#6]
As a **Site User** I can **click on a recipe** so that **I can view the full recipe details**

### Acceptance Criteria

- When a user clicks on a the image of a recipe, a detailed recipe post is visible
- When a user clicks on a the title of a recipe, a detailed recipe post is visible
- Recipe detail need to be easy to read and well structured

### Tasks

- [x] Create a Recipe template for consistency of all recipes in the webpage
- [x] Style the Recipe templates
- [x] Ensure the recipe templates are clear to understand
