### ISSUE TITLE
Add and manage Recipe posts

### ISSUE THREAD

**Issue by NicoleJackson89** [NicoleJackson89/pp4-recipe-share#7]
As a **Site User** I can **add and manage my own recipes** so that **I can share my recipes with others**

### Acceptance Criteria

- Users can add new recipe posts
- Users can add an image to the recipe post, if one is not supplied a placeholder image will be used
- Users can update recipe posts (Should have)
- Users can delete their own recipe posts, a confirmation notification pops up before hand for better user experience (Should have)
- Users can save to continue later or publish their recipes to be updated to the site immediately (Could have)

### Tasks

- [x] Add a Recipe model
- [x] Add full CRUD functionality on the recipes they add
- [x] Add functionality to upload images with placeholders where one is not supplied
- [x] Create a confirmation notification on delete
