### ISSUE TITLE
My Profile

### ISSUE THREAD

**Issue by NicoleJackson89** [NicoleJackson89/pp4-recipe-share#9]
As a **Site User** I can **manage my profile** so that **I can update and view my details**

### Acceptance Criteria

- Users can view and update their profile
- Users can access their profile from the navigation bar
- Users can delete their profile if they want to do so

### Tasks

- [ ] Add a My Profile model
- [ ] Add read and update functionality
- [ ] Add delete functionality

**Comment by NicoleJackson89** [comment]
Future Feature
